const products = [
	{
		_id: '1',
		name: 'CBC Honeysuckle Sauce',
		image: '/images/stretched-honey.jpeg',
		description:
			'Honeysuckle, or Sulla, is delicately sweet and slightly floral with vegetal notes of straw or dry grass. It can be thick and sticky to only slightly viscous.',
		brand: 'CBC',
		category: 'Honey',
		price: 15.99,
		countInStock: 5,
		rating: 4.5,
		numReviews: 16,
	},
	{
		_id: '2',
		name: 'CBC Wildflower Honey Chunks',
		image: '/images/chunkCrystallized-honey.jpeg',
		description:
			'Wildflower honeys are the product of an infinite combination of nectars, whose colors, scents and aromas are like snapshots of the habitats they come from.',
		brand: 'CBC',
		category: 'Honey',
		price: 19.5,
		countInStock: 7,
		rating: 4.0,
		numReviews: 8,
	},
	{
		_id: '3',
		name: 'CBC Wild Citrus Raw Sugar Honey',
		image: '/images/spoonCrystallized-honey.jpeg',
		description:
			'Citrus honey is tangy, fruity, floral, heady, and sophisticated. It has a hint of mysterious, exotic perfume on the finish, similar to bergamot oil, but very faint.',
		brand: 'CBC',
		category: 'Honey',
		price: 29.99,
		countInStock: 15,
		rating: 5,
		numReviews: 7,
	},
	{
		_id: '4',
		name: 'CBC Tupelo Honey Butter',
		image: '/images/spread-honey.jpeg',
		description:
			"Tupelo honey's buttery undertones is somehow sweeter than other types of honey but with a lovely balanced mild flavor.",
		brand: 'CBC',
		category: 'Honey',
		price: 10.99,
		countInStock: 7,
		rating: 3.5,
		numReviews: 7,
	},
	{
		_id: '5',
		name: 'CBC Lavender Infused Honey',
		image: '/images/manuka-honey.jpeg',
		description:
			'Lavender-infused honey has a sweet and lightly floral flavor. Lavender also has a long medicinal history, predominantly used for its calming effects. We like to think our lavender honey infusion sweetens the results.',
		brand: 'CBC',
		category: 'Honey',
		price: 10.99,
		countInStock: 1,
		rating: 4,
		numReviews: 12,
	},
	{
		_id: '6',
		name: 'CBC Blackberry Honey Rock Candy',
		image: '/images/crystalizedRod-honey.jpeg',
		description:
			'This honey is multifloral, it ranges in color from a deep amber to a lighter, golden caramel color. Some are intensely aromatic with a floral and herbaceous flavor, and some have a fruity and citrus flavor.',
		brand: 'CBC',
		category: 'Honey',
		price: 20.99,
		countInStock: 0,
		rating: 4,
		numReviews: 12,
	},
	{
		_id: '7',
		name: 'CBC Sweet Vanilla Honey',
		image: '/images/spoolerChunk-honey.jpeg',
		description:
			'Vanilla is one of the most popular flavorings in the whole world, so it’s no wonder why vanilla and honey make a great combination. Our vanilla-infused honey is made from fresh ground Madagascar vanilla beans set into pure, raw honey. The resulting vanilla honey flavor is deep, rich, and oh so sweet.',
		brand: 'CBC',
		category: 'Honey',
		price: 19.99,
		countInStock: 12,
		rating: 5,
		numReviews: 11,
	},
	{
		_id: '8',
		name: 'CBC Dandelion Honey Butter',
		image: '/images/crystallized-honey.jpg',
		description:
			'Dandelion Honey, made from raw, unpasteurized wild dandelion, delivers a strong, tangy zing of rich flavor. The aroma is strong with medium sweetness and a slightly astringent lingering aftertaste that has been described as refreshing.',
		brand: 'CBC',
		category: 'Honey',
		price: 25.5,
		countInStock: 9,
		rating: 4.5,
		numReviews: 10,
	},
	{
		_id: '9',
		name: 'CBC Orange Blossom Honey',
		image: '/images/granulated-honey.jpeg',
		description:
			"Orange Blossom Honey is floral, fruity, and incredibly aromatic. This fragrant, light amber honey comes from sunny Central Florida, an area of the US famous for its abundance of orange groves. It's like sunshine in a jar!",
		brand: 'CBC',
		category: 'Honey',
		price: 12.5,
		countInStock: 7,
		rating: 4,
		numReviews: 9,
	},
];

export default products;
