const products = [
	{
		_id: '1',
		name: 'Airpods Bluetooth Headphones',
		image: '/images/airpods.jpg',
		description:
			'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
		brand: 'Apple',
		category: 'Electronics',
		price: 89.99,
		countInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: '2',
		name: 'iPhone 11 Pro 256GB Memory',
		image: '/images/phone.jpg',
		description:
			'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
		brand: 'Apple',
		category: 'Electronics',
		price: 599.99,
		countInStock: 7,
		rating: 4.0,
		numReviews: 8,
	},
	{
		_id: '3',
		name: 'Cannon EOS 80D DSLR Camera',
		image: '/images/camera.jpg',
		description:
			'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
		brand: 'Cannon',
		category: 'Electronics',
		price: 929.99,
		countInStock: 5,
		rating: 3,
		numReviews: 12,
	},
	{
		_id: '4',
		name: 'Sony Playstation 4 Pro White Version',
		image: '/images/playstation.jpg',
		description:
			'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
		brand: 'Sony',
		category: 'Electronics',
		price: 399.99,
		countInStock: 11,
		rating: 5,
		numReviews: 12,
	},
	{
		_id: '5',
		name: 'Logitech G-Series Gaming Mouse',
		image: '/images/mouse.jpg',
		description:
			'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
		brand: 'Logitech',
		category: 'Electronics',
		price: 49.99,
		countInStock: 7,
		rating: 3.5,
		numReviews: 10,
	},
	{
		_id: '6',
		name: 'Amazon Echo Dot 3rd Generation',
		image: '/images/alexa.jpg',
		description:
			'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
		brand: 'Amazon',
		category: 'Electronics',
		price: 29.99,
		countInStock: 0,
		rating: 4,
		numReviews: 12,
	},
	{
		_id: '7',
		name: 'CBC Orange Blossom Honey Sauce',
		image: '/images/honey-spoon.jpg',
		description:
			"Orange Blossom Honey Sauce is floral, fruity, and incredibly aromatic. This fragrant, light amber honey comes from sunny Central Florida, an area of the US famous for its abundance of orange groves. It's like sunshine in a jar!",
		brand: 'CBC',
		category: 'Honey',
		price: 12.5,
		countInStock: 7,
		rating: 4,
		numReviews: 9,
	},
	{
		_id: '8',
		name: 'CBC Sweet Vanilla Honey',
		image: '/images/honey-spooler.jpg',
		description:
			'Vanilla is one of the most popular flavorings in the whole world, so it’s no wonder why vanilla and honey make a great combination. Our vanilla-infused honey is made from fresh ground Madagascar vanilla beans set into pure, raw honey. The resulting vanilla honey flavor is deep, rich, and oh so sweet.',
		brand: 'CBC',
		category: 'Honey',
		price: 19.99,
		countInStock: 12,
		rating: 5,
		numReviews: 11,
	},
	{
		_id: '9',
		name: 'CBC Dandelion Honey Butter',
		image: '/images/crystallized-honey.jpg',
		description:
			'Dandelion Honey, made from raw, unpasteurized wild dandelion, delivers a strong, tangy zing of rich flavor. The aroma is strong with medium sweetness and a slightly astringent lingering aftertaste that has been described as refreshing.',
		brand: 'CBC',
		category: 'Honey',
		price: 25.5,
		countInStock: 9,
		rating: 4.5,
		numReviews: 10,
	},
];

export default products;
